"""SQLAlchemy models package initialization.
Exports all models to ensure complete declarative mapper registry configuration.
"""

from app.models.user import (
    User,
    UserRole,
    AuthProvider,
    UserSession,
    OTPCode,
    OTPPurpose,
    CustomRequest,
    CustomRequestStatus,
    AIChatSession,
    AIChatMessage,
    AIUsage,
    Notification,
    NotificationChannel,
    AuditLog,
    StorePolicy,
    StoreSetting,
)
from app.models.product import (
    Category,
    Product,
    ProductVariant,
    ProductImage,
    ProductReview,
    ProductReviewSummary,
)
from app.models.order import (
    Order,
    OrderStatus,
    OrderItem,
    InventoryReservation,
    ReservationStatus,
    InventoryTransaction,
    InventoryTransactionType,
    Coupon,
    CouponType,
    CouponRedemption,
    Payment,
    PaymentStatus,
    PaymentEvent,
)
from app.models.cart import (
    Cart,
    CartItem,
)

__all__ = [
    "User",
    "UserRole",
    "AuthProvider",
    "UserSession",
    "OTPCode",
    "OTPPurpose",
    "CustomRequest",
    "CustomRequestStatus",
    "AIChatSession",
    "AIChatMessage",
    "AIUsage",
    "Notification",
    "NotificationChannel",
    "AuditLog",
    "StorePolicy",
    "StoreSetting",
    "Category",
    "Product",
    "ProductVariant",
    "ProductImage",
    "ProductReview",
    "ProductReviewSummary",
    "Order",
    "OrderStatus",
    "OrderItem",
    "InventoryReservation",
    "ReservationStatus",
    "InventoryTransaction",
    "InventoryTransactionType",
    "Coupon",
    "CouponType",
    "CouponRedemption",
    "Payment",
    "PaymentStatus",
    "PaymentEvent",
    "Cart",
    "CartItem",
]
